### ISSUE TITLE
使用 http://httpbin.org/ip 测试，每次都返回的同一个地址，怎么解决？

### ISSUE THREAD

**Issue by jobbofhe** [xNathan/squid_proxy_pool#2]
我有300个代理IP, 执行脚本，30s替换一次squid.conf 文件
每次配置文件，修改这句代码
`cache_peer %s parent %s 0 no-query weighted-round-robin weight=1 connect-fail-limit=2 allow-miss 
max-conn=5`

但是每次返回的结果都是同一个IP, 
`
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Cache-Control": "max-age=259200", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.23.0", 
    "X-Amzn-Trace-Id": "Root=1-5e96e54e-df32076cdb1d363266ba7550"
  }, 
  "origin": "172.25.0.1, 112.17.x.x", 
  "url": "http://httpbin.org/get"
}

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Cache-Control": "max-age=259200", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.23.0", 
    "X-Amzn-Trace-Id": "Root=1-5e96e552-f77a0f94ce2183b8b0e1ea48"
  }, 
  "origin": "172.25.0.1, 112.17.x.x", 
  "url": "http://httpbin.org/get"
}
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip, deflate", 
    "Cache-Control": "max-age=259200", 
    "Host": "httpbin.org", 
    "User-Agent": "python-requests/2.23.0", 
    "X-Amzn-Trace-Id": "Root=1-5e96e555-c3fe13887b2580e5c6d48e05"
  }, 
  "origin": "172.25.0.1, 112.17.x.x", 
  "url": "http://httpbin.org/get"
}`

完全按照你的方法配置的，请问这个问题，你有遇到过吗？

**Comment by xNathan** [comment]
可能代理本身有问题，试试直接在 requests 设置 proxy 为代理地址，能代理成功吗

**Comment by jobbofhe** [comment]
确实是代理本身的问题， 已经解决了，谢谢了
